# AUTH
POST  http://localhost:3001/auth/register
Content-Type: application/json

{
   "name":"Ilham",
   "surname":"Quluzada",
   "email":"ilham@amail.az",
   "password":"qwerty23"
}

###
POST  http://localhost:3001/auth/login
Content-Type: application/json

{
   "email":"test23@amail.az",
   "password":"qwerty23"
}





# USER
###
POST  http://localhost:3001/user/add-to-basket/61144110af432a0e3c27029b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyM0BhbWFpbC5heiIsImlkIjoiNjA4NzM4MjIyYmM3M2MzNjBjM2JmMDZkIiwiaWF0IjoxNjI4Nzc1NjI3LCJleHAiOjE2Mjg3NzkyMjd9.14RSza96mixaAtj_UxHM7o_Ok_XOTCvG-22-BPcYNqM
Content-Type: application/json
### 
DELETE   http://localhost:3001/user/remove-from-basket/61144134af432a0e3c27029f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyM0BhbWFpbC5heiIsImlkIjoiNjA4NzM4MjIyYmM3M2MzNjBjM2JmMDZkIiwiaWF0IjoxNjI4Nzc1NjI3LCJleHAiOjE2Mjg3NzkyMjd9.14RSza96mixaAtj_UxHM7o_Ok_XOTCvG-22-BPcYNqM
Content-Type: application/json


###
GET   http://localhost:3001/user/get-basket
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyM0BhbWFpbC5heiIsImlkIjoiNjA4NzM4MjIyYmM3M2MzNjBjM2JmMDZkIiwiaWF0IjoxNjI4Nzc1NjI3LCJleHAiOjE2Mjg3NzkyMjd9.14RSza96mixaAtj_UxHM7o_Ok_XOTCvG-22-BPcYNqM
Content-Type: application/json

###
PUT    http://localhost:3001/user/edit-address
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyM0BhbWFpbC5heiIsImlkIjoiNjA4NzM4MjIyYmM3M2MzNjBjM2JmMDZkIiwiaWF0IjoxNjI4Nzc1NjI3LCJleHAiOjE2Mjg3NzkyMjd9.14RSza96mixaAtj_UxHM7o_Ok_XOTCvG-22-BPcYNqM
Content-Type: application/json

{
  "address_line_1":"Razinn",
  "address_line_2":"234",
  "post_code":"az2342",
  "phone_number":"29349294234",
  "country": "Azeer",
  "city": "Bakuu"
}


# COMPOSER
### 
POST  http://localhost:3001/composer
Content-Type: application/json

{
   "fullname":"GUY HAWKINSasdasd",
   "job": "composer234",
   "description": "As a composer for media, Drew has produced music and sonic branding for numerous world brands and media conglomerates. He is also an active concert composer and sound artist with a diverse range of international commissions and exhibits. Revered by his peers, industry professionals, and critics, his work has been called both “rare” and “remarkable.” “This composer bends and stretches rules within his own aesthetic, weaving his musical ideas in harmonious waves that threaten to drown, yet gently tumble the listener forward with intrigue and anticipation.” -Adam Rosenthal review for Persee: Orchestrated Perception I think we shall meet!",
   "photo_url": "https://qasham.github.io/justforhorns/assets/images/composer1.png",
   "country": "Azerbaijan"
  
}
###
GET  http://localhost:3001/composer
Content-Type: application/json


# OFFER
### 
POST  http://localhost:3001/offer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyM0BhbWFpbC5heiIsImlkIjoiNjA4NzM4MjIyYmM3M2MzNjBjM2JmMDZkIiwiaWF0IjoxNjI4Nzc1NjI3LCJleHAiOjE2Mjg3NzkyMjd9.14RSza96mixaAtj_UxHM7o_Ok_XOTCvG-22-BPcYNqM

{
   "status":false,
   "items": [
      {
         "count":1,
         "product":"61144110af432a0e3c27029b"
         },
          {
         "count":2,
         "product":"60889b12a0a53e0cfc9280be"
         }
   ]
  
}
###
GET  http://localhost:3001/offer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyM0BhbWFpbC5heiIsImlkIjoiNjA4NzM4MjIyYmM3M2MzNjBjM2JmMDZkIiwiaWF0IjoxNjI4Nzc1NjI3LCJleHAiOjE2Mjg3NzkyMjd9.14RSza96mixaAtj_UxHM7o_Ok_XOTCvG-22-BPcYNqM
Content-Type: application/json





# PRODUCT
###

POST  http://localhost:3001/product
Content-Type: application/json

{
   "name":"Fantasie über Themen aus Giuseppe Verdis Rigoletto",
   "genre":"Classical",
   "composers":["608747a87362c828b08f66ac"],
   "description":"This digital sheet music was either arranged by Dan Turcan staff of professional arrangers and composers or it is a new engraving of the composition's original printed arrangement. Revered by his peers, industry professionals, and critics, his work has been called both “rare” and “remarkable. ”This composer bends and stretches rules within his own aesthetic, weaving his musical ideas in harmonious waves that threaten to drown, yet gently tumble the listener forward with intrigue and anticipation.",
   "audio_url":"http://cld3097web.audiovideoweb.com/va90web25003/companions/Foundations%20of%20Rock/3.01.mp3",
   "price":24.5,
   "instruments":["60884ac41e2b3b33ac554ddd"],
   "pages":121,
   "release_date":"2021-08-27T19:57:25.508Z",
   "media_list":[
       {
          "isVideo": false,
          "thumbnail": "https://qasham.github.io/justforhorns/assets/images/pdfPreviewImg.png",
          "url": "https://qasham.github.io/justforhorns/assets/images/pdfPreviewImg.png"
        },
        {
          "isVideo": false,
          "thumbnail": "https://qasham.github.io/justforhorns/assets/images/pdfPreviewImg.png",
          "url": "https://qasham.github.io/justforhorns/assets/images/pdfPreviewImg.png"
        },
        {
          "isVideo": true,
          "thumbnail": "https://qasham.github.io/justforhorns/assets/images/videoPreviewImg.png",
          "url": "https://www.youtube.com/watch?v=tkABhOWSeak&list=RDtkABhOWSeak&start_radio=1"
        }
   ]
}

###
GET  http://localhost:3001/product
Content-Type: application/json

###
GET  http://localhost:3001/product/60889b12a0a53e0cfc9280be
Content-Type: application/json
